In [1]:
from base import Rangel
from rangel import RangeCollection
import numpy as np
import pandas as pd
import geopandas as gpd

In [2]:
df_linear_1 = pd.DataFrame({
    'route': ['Main St', 'Main St', 'Main St', '1st Ave', '1st Ave', '2nd Ave', '2nd Ave', 'Sycamore School Rd'],
    'beg': [0.0, 0.5, 1.1, 10.0, 12.0, 13.0, 13.1, 1.8],
    'end': [0.4, 1.1, 3.0, 12.0, 13.0, 13.1, 14.0, 3.0],
    'volume': [100, 200, 100, 400, 500, 150, 200, 800],
})
df_linear_2 = pd.DataFrame({
    'route': ['Main St', 'Main St', '1st Ave', '2nd Ave', '2nd Ave', 'Sycamore School Rd'],
    'beg': [0.0, 1.0, 10.0, 13.0, 13.1, 2.2],
    'end': [1.0, 2.0, 12.0, 13.0, 14.0, 2.8],
    'class': ['A', 'B', 'A', 'A', 'B', 'A'],
})

In [3]:
rng1 = Rangel(index=df_linear_1.index, groups=df_linear_1.route, begs=df_linear_1.beg, ends=df_linear_1.end, closed='left_mod')
rng2 = Rangel(index=df_linear_2.index, groups=df_linear_2.route, begs=df_linear_2.beg, ends=df_linear_2.end, closed='left_mod')

In [4]:
rc1 = RangeCollection(begs=df_linear_1.beg, ends=df_linear_1.end, closed='left_mod')
rc2 = RangeCollection(begs=df_linear_2.beg, ends=df_linear_2.end, closed='left_mod')

In [5]:
%%timeit
rng1.overlay(rng2, normalize=True, norm_by='right')

23.3 µs ± 802 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [6]:
%%timeit
rc1.overlay(rc2.begs, rc2.ends, normalize=True, norm_by='right')

29.6 µs ± 283 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [23]:
rng1.overlay(rng2, normalize=True, norm_by='right') == rc1.overlay(rc2.begs, rc2.ends, normalize=True, norm_by='right')

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [6]:
rng1.overlay(rng2, normalize=True, norm_by='right')

array([[0.4, 0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.1, 0. , 0. , 0. , 0. ],
       [0. , 0.9, 0. , 0. , 0. , 0. ],
       [0. , 0. , 1. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 1. ]])

In [26]:
display(df_linear_1)
display(df_linear_2)

                route   beg   end  volume
0             Main St   0.0   0.4     100
1             Main St   0.5   1.1     200
2             Main St   1.1   3.0     100
3             1st Ave  10.0  12.0     400
4             1st Ave  12.0  13.0     500
5             2nd Ave  13.0  13.1     150
6             2nd Ave  13.1  14.0     200
7  Sycamore School Rd   1.8   3.0     800

                route   beg   end class
0             Main St   0.0   1.0     A
1             Main St   1.0   2.0     B
2             1st Ave  10.0  12.0     A
3             2nd Ave  13.0  13.0     A
4             2nd Ave  13.1  14.0     B
5  Sycamore School Rd   2.2   2.8     A

In [ ]:
size = 1000
l1 = np.arange(0, size, 1).reshape(-1, 1)
l2 = np.arange(0, size, 1).reshape(1, -1)
arr = np.arange(0, size**2, 1).reshape(size, size)

In [ ]:
%%timeit
x = np.minimum(l1, l2)
np.where(arr > x, x, arr)

In [ ]:
%%timeit
x = np.minimum(l1, l2)
x = np.minimum(arr, x)

In [ ]:
%%timeit
x = np.minimum(l1, l2)
np.minimum(arr, x, out=arr)

In [ ]:
(arr > l1) | (arr > l2)

In [ ]:
%%timeit
np.nanmin(np.stack([arr, np.tile(l1, (1, size)), np.tile(l2, (size, 1))], axis=0), axis=0)

In [ ]:
np.tile(l1, (1, 100)).shape

In [ ]:
n = 10000
begs = np.random.randint(0, n, n)
ends = begs + np.random.randint(1, 10, n)
adj = int(n / 1.2)
rng1 = Rangel(begs=begs, ends=ends, closed='left_mod')
rng2 = Rangel(begs=begs + adj, ends=ends + adj, closed='left_mod')
rc1 = RangeCollection(begs=begs, ends=ends, closed='left_mod')
rc2 = RangeCollection(begs=begs + adj, ends=ends + adj, closed='left_mod')

In [ ]:
%%timeit
rng1.intersecting(rng2, enforce_edges=True)

In [ ]:
%%timeit
rc1.intersecting(rc2)